png("plot_ex5.png",width = 600)
set.seed(14)
x <- rf(300,df1 = 3,df2 = 50)
e <- rnorm(300,mean = 0,sd = 4)
y <- 5 + 3 * x + e
median.x <- median(x)
print(median.x)
median.y <- median(y)
print(median.y)
layout(matrix(c(1,2,2,1,2,2,4,3,3),nrow = 3,byrow = T))
boxplot(y,pch = 20,cex = 1,col = "purple")
plot(x,y,abline(v = median.x,h = median.y,lty = 1),pch = 20,cex = 2,col = "purple")
boxplot(x,pch = 20,cex = 1,horizontal = T,col = "purple")
dev.off()
