png("plot_ex6.png",width = 600)
par(mfrow = c(2,1))
set.seed(14)
a <- c(0, 0.13)
x <- rf(300,df1 = 3,df2 = 50)
hist(x,freq = F,col = "deepskyblue1")
curve(df(x,df1 = 3,df2 = 50),col = "black",lwd = 2,add = T)
lines(density(x),col = "red",lwd = 2)
e <- rnorm(300,mean = 0,sd = 4)
hist(e,freq = F,col = "deepskyblue1", ylim = a)
curve(dnorm(x,mean = 0,sd = 4),col = "black",lwd = 2,add = T)
lines(density(e),col = "red",lwd = 2)
par(mfrow = c(1,1))
dev.off()
?curve
